apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: first
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  spec:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
  template:
    metadata:
      labels:
        app: nginx
      containers:
        - name: nginx
          image: rekvv/grapefield_front:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: shared-storage
              mountPath: /usr/share/nginx/html/uploads
            - name: ssl-secret-volume
              mountPath: /etc/nginx/ssl
              readOnly: true
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-image-vol
        - name: ssl-secret-volume
          secret:
            secretName: front-tls-secret
